/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Classification = IDL.Variant({
  'conservative' : IDL.Null,
  'aggressive' : IDL.Null,
  'moderate' : IDL.Null,
});
export const InvestmentRecommendation = IDL.Record({
  'stocks' : IDL.Nat,
  'cash' : IDL.Nat,
  'description' : IDL.Text,
  'bonds' : IDL.Nat,
});

export const idlService = IDL.Service({
  'classifyProfile' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [Classification],
      [],
    ),
  'generateRecommendation' : IDL.Func(
      [Classification],
      [InvestmentRecommendation],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Classification = IDL.Variant({
    'conservative' : IDL.Null,
    'aggressive' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const InvestmentRecommendation = IDL.Record({
    'stocks' : IDL.Nat,
    'cash' : IDL.Nat,
    'description' : IDL.Text,
    'bonds' : IDL.Nat,
  });
  
  return IDL.Service({
    'classifyProfile' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [Classification],
        [],
      ),
    'generateRecommendation' : IDL.Func(
        [Classification],
        [InvestmentRecommendation],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };